### ISSUE TITLE
nvme_snsd实现与ODCC－2020－05016《NVME over RoCEv2网络控制优化技术要求与测试规范》不一致问题

### ISSUE THREAD

**Issue by InfiniteFaith** [linux-nvme/nvme-snsd#10]
SNSD软件状态通知报文实现已过时，请更新实现
1. 当前SNSD软件实现状态通知消息格式中的协议版本号为0，而ODCC协议已经更新到1了。
2. 协议版本0和协议版本1的区别如下：
 - 设备状态: 最新版本修改Value长度为4字节
 - 设备状态变换原因: 最新版本修改value长度为4字节

**Comment by Tao191** [comment]
We will update support in the near future,thanks

**Comment by Weislley** [comment]
Did we fix the issue?

**Comment by danieldin95** [comment]
> SNSD软件状态通知报文实现已过时，请更新实现
> 
> 1. 当前SNSD软件实现状态通知消息格式中的协议版本号为0，而ODCC协议已经更新到1了。
> 2. 协议版本0和协议版本1的区别如下：
> 
> * 设备状态: 最新版本修改Value长度为4字节
> * 设备状态变换原因: 最新版本修改value长度为4字节

你好！我也在研究SNSD，正好看到你的评论，关于ODCC的协议方便发送给我一份参考？非常感谢！

**Comment by InfiniteFaith** [comment]
> > SNSD软件状态通知报文实现已过时，请更新实现
> > 
> > 1. 当前SNSD软件实现状态通知消息格式中的协议版本号为0，而ODCC协议已经更新到1了。
> > 2. 协议版本0和协议版本1的区别如下：
> > 
> > 
> > * 设备状态: 最新版本修改Value长度为4字节
> > * 设备状态变换原因: 最新版本修改value长度为4字节
> 
> 你好！我也在研究SNSD，正好看到你的评论，关于ODCC的协议方便发送给我一份参考？非常感谢！
[Uploading ODCC-2020-05016 NVMe over RoCEv2网络控制优化技术要求与测试规范.pdf…]()

**Comment by danieldin95** [comment]
> > > SNSD软件状态通知报文实现已过时，请更新实现
> > > 
> > > 1. 当前SNSD软件实现状态通知消息格式中的协议版本号为0，而ODCC协议已经更新到1了。
> > > 2. 协议版本0和协议版本1的区别如下：
> > > 
> > > 
> > > * 设备状态: 最新版本修改Value长度为4字节
> > > * 设备状态变换原因: 最新版本修改value长度为4字节
> > 
> > 
> > 你好！我也在研究SNSD，正好看到你的评论，关于ODCC的协议方便发送给我一份参考？非常感谢！
> > Uploading ODCC-2020-05016 NVMe over RoCEv2网络控制优化技术要求与测试规范.pdf…

打扰了，我尝试点击下载链接，并没有下载成功，方便的话可以发送到我的个人邮箱：danieldin95@163.com 么？

**Comment by Tao191** [comment]
是的，版本v1是已经支持的。参考：SNSD_NT_STATE_LEN_V0/SNSD_NT_STATE_LEN_V1.
